### ISSUE TITLE
試してみようと思っています

### ISSUE THREAD

**Issue by zukakosan** [yh0sh/CorrLDA#1]
mportError: dlopen(./corr_lda.so, 2): no suitable image found.  Did find:
	./corr_lda.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/(Username)/Desktop/python2/CorrLDA-master/corr_lda.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
このようなエラーが出るのですが原因などはわかりますでしょうか？
当方初心者でして．

**Comment by yh0sh** [comment]
MacOS依存のエラーのようです．
自分はUbuntu使っていて，Mac使いではないので解決法は分かりません・・・すいません．
見た感じでコンパイルエラーっぽいので，一度コンパイルしてpycを作り直してもらえるでしょうか?
